export const types = {
    // User types
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_USER: 'SET_USER',
    SET_QUOTA: 'SET_QUOTA',
    LOADING_USER: 'LOADING_USER',
    EDIT_METRIC: 'EDIT_METRIC',
    // UI types
    SET_ERRORS: 'SET_ERRORS',
    LOADING_UI: 'LOADING_UI',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}